export const RANDOMIZE_KINGDOM_COST = 1000
export const CRAFTING_FOOD_STORAGE_LIMIT = Number(process.env.CRAFTING_FOOD_STORAGE_LIMIT) || 20000
export const CRAFTING_FOOD_REQUIRED_BASE = Number(process.env.CRAFTING_FOOD_REQUIRED_BASE) || 100
export const CRAFTING_FOOD_NUTRITION_BASE = Number(process.env.CRAFTING_FOOD_NUTRITION_BASE) || 100
